sudo: required
dist: trusty
language: python
python:
  - "2.7"

script: ansible-playbook workstation.yml -vv

before_script:
    - sudo add-apt-repository ppa:ansible/ansible --yes
    - sudo apt-get update
    - sudo apt-get install ansible --yes 
    - rm -rf ~/.vim
    - rm -rf ~/.ssh
