sudo: required
dist: trusty
language: python
python:
  - "2.7"

script:
     - "apt-cache search pcsx2 | grep pcsx2 && (echo 'pcsx2 is available. test: pass' && exit 0) || (echo 'pcsx2 is unavailable test: fail' && exit 1)"
#     - ansible-playbook workstation.yml --syntax-check
#     - ansible-playbook workstation.yml -vvvv --sudo

before_script:
     - sudo apt-add-repository --yes ppa:gregory-hainaut/pcsx2.official.ppa
     - ls /etc/apt/sources.list.d/
     - sudo apt-get update
     - apt-cache policy
     - apt-cache showpkg pcsx2
     - sudo apt-get install pcsx2 --yes --print-uris
     - sudo apt-get install pcsx2 --yes
#    - pip install pip setuptools wheel -U -q
#    - pip install ansible -q
#    - rm -rf ~/.vim
#    - rm -rf ~/.ssh
