sudo: required
dist: trusty
language: python
python:
  - "2.7"

services:
  - docker

script:
     - ansible-playbook workstation.yml --syntax-check
     - ansible-playbook workstation.yml -vvvv --sudo

before_script:
    - pip install pip setuptools wheel -U -q
    - pip install ansible -q

