sudo: required
dist: trusty
language: python
python:
  - "2.7"

script: ansible-playbook workstation.yml -vv

before_script:
    - pip install pip setuptools wheel -U
    - pip install ansible 
    - rm -rf ~/.vim
    - rm -rf ~/.ssh
