- name: ensure apt-fast repository is installed
  apt_repository: repo='ppa:saiarcot895/myppa' state=present
  when: ansible_distribution == 'Ubuntu'
  become: yes
  become_method: sudo

- name: update apt packages cache
  apt: update_cache=yes
  when: ansible_distribution == 'Ubuntu'
  become: yes
  become_method: sudo

- name: ensure apt-fast is installed
  apt: name=apt-fast state=present
  when: ansible_distribution == 'Ubuntu'
  become: yes
  become_method: sudo

