FROM ubuntu:xenial-20160314.4
RUN apt-get update

# add support to 32bit packages
RUN dpkg --add-architecture i386
# Install Ansible
RUN apt-get update
RUN apt-get install -y software-properties-common python-pip python-dev build-essential
RUN pip install ansible

# Install Ansible inventory file
RUN mkdir -p /etc/ansible/
RUN echo "[home]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
RUN echo "[defaults]\nhostfile=./hosts" > /etc/ansible/ansible.cfg

