FROM ubuntu:14.04
RUN apt-get update

# Install Ansible
RUN apt-get update
RUN apt-get install -y software-properties-common python-pip python-dev build-essential
RUN pip install ansible

# Install Ansible inventory file
RUN echo "[home]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
RUN echo "[defaults]\nhostfile=./hosts" > /etc/ansible/ansible.cfg


