- name: ensure pcsx2 repository is installed
  apt_repository: repo='ppa:gregory-hainaut/pcsx2.official.ppa' state=present
  when: ansible_distribution == 'Ubuntu'
  become: yes
  become_method: sudo

- name: update apt packages cache
  apt: update_cache=yes
  when: ansible_distribution == 'Ubuntu'
  become: yes
  become_method: sudo

- name: ensure pcsx2 is installed
  apt: name=pcsx2 state=present
  when: ansible_distribution == 'Ubuntu'
  become: yes
  become_method: sudo

