- name: ensure pcsx2 ppa:gregory-hainaut/pcsx2.official.ppa repository is installed
  apt_repository: repo='ppa:gregory-hainaut/pcsx2.official.ppa' state=present
  when: ansible_distribution == 'Ubuntu'
  become: yes
  become_method: sudo

- name: update apt packages cache
  apt: update_cache=yes
  when: ansible_distribution == 'Ubuntu'
  become: yes
  become_method: sudo

# pacotes 32bits necessitam ser explicitamente indicados no ansible
- name: ensure pcsx2:i386 is installed
  apt: name=pcsx2:i386 state=present force=yes
  when: ansible_distribution == 'Ubuntu'
  become: yes
  become_method: sudo

