- name: ensure simplescreenrecorder repository is installed
  apt_repository: repo='ppa:maarten-baert/simplescreenrecorder' state=present
  when: ansible_distribution == 'Ubuntu'
  become: yes
  become_method: sudo

- name: update apt packages cache
  apt: update_cache=yes
  when: ansible_distribution == 'Ubuntu'
  become: yes
  become_method: sudo

- name: ensure simplescreenrecorder is installed
  apt: name=simplescreenrecorder state=present
  when: ansible_distribution == 'Ubuntu'
  become: yes
  become_method: sudo

