- name: ensure git is installed
  apt: name=git state=present
  become: yes
  become_method: sudo

- name: be sure git is configured
  template: src=gitconfig.j2 dest={{ ansible_env.HOME }}/.gitconfig owner={{ ansible_user_id }}
