- name: ensure ppa:caffeine-developers/ppa repository is installed
  apt_repository: repo='ppa:caffeine-developers/ppa' state=present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
  become: yes
  become_method: sudo

- name: update apt packages cache
  apt: update_cache=yes
  when: ansible_distribution == 'Ubuntu'
  become: yes
  become_method: sudo

- name: ensure caffeine is installed
  apt: name=caffeine state=present force=yes
  when: ansible_distribution == 'Ubuntu'
  become: yes
  become_method: sudo

